### ISSUE TITLE
Harcore Survival Mod still not working properly with your mod

### ISSUE THREAD

**Issue by QuImUfu** [KidsDontPlay/BlockDrops#15]
Well... In some way it does work but it spams the console and the log file with this message everytime it tests another block (this means "5000"*"amount of tested blocks"*"3" (levels of fortune)):

```
[22:11:31] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent@cae7549:
java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
    at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93) ~[Event.class:?]
    at mod.upcraftlp.hardcoresurvival.util.WoodEvents.onWoodBroken(WoodEvents.java:21) ~[WoodEvents.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_59_WoodEvents_onWoodBroken_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:226) [ForgeEventFactory.class:?]
    at mrriegel.blockdrops.Plugin.getList(Plugin.java:104) [Plugin.class:?]
    at mrriegel.blockdrops.Plugin.getRecipes(Plugin.java:77) [Plugin.class:?]
    at mrriegel.blockdrops.BlockDrops.postInit(BlockDrops.java:125) [BlockDrops.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:577) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:191) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[22:11:31] [Client thread/ERROR]: Index: 5 Listeners:
[22:11:31] [Client thread/ERROR]: 0: HIGHEST
[22:11:31] [Client thread/ERROR]: 1: ASM: com.oitsjustjose.vtweaks.enchantment.EnchantmentAutosmeltHandler@1f6460f5 register(Lnet/minecraftforge/event/world/BlockEvent$HarvestDropsEvent;)V
[22:11:31] [Client thread/ERROR]: 2: NORMAL
[22:11:31] [Client thread/ERROR]: 3: ASM: com.oitsjustjose.vtweaks.event.blocktweaks.CakeTweak@643ee419 registerTweak(Lnet/minecraftforge/event/world/BlockEvent$HarvestDropsEvent;)V
[22:11:31] [Client thread/ERROR]: 4: ASM: mod.upcraftlp.hardcoresurvival.util.LeafEvents@3d8cef0c onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$HarvestDropsEvent;)V
[22:11:31] [Client thread/ERROR]: 5: ASM: mod.upcraftlp.hardcoresurvival.util.WoodEvents@16c3c7db onWoodBroken(Lnet/minecraftforge/event/world/BlockEvent$HarvestDropsEvent;)V
[22:11:31] [Client thread/ERROR]: 6: ASM: sblectric.lightningcraft.events.ToolEvents@ac284a8 onHarvestDrops(Lnet/minecraftforge/event/world/BlockEvent$HarvestDropsEvent;)V
```

It does work if i set the iteration value to one and i think it would work with 5000 (default), too. but it takes very long because of all the errors (30min+ , stopped trying, but it would take nearly one day, if i calculated it right ^^(ca 15 sec with iteration=1 => ca 20 hours with iteration=5000 ).

**Comment by KidsDontPlay** [comment]
Is it fixed with the latest version?

**Comment by QuImUfu** [comment]
The 1.0.10 version does not throw these errors and does not show the changes to the leave drops hardcoresurvival does.  
If this is intentional and i should just add them by hand, this issue is solved.

**Comment by KidsDontPlay** [comment]
It's not intentional but some mods are not compatible
