### ISSUE TITLE
Ore chunks from How Fortunate incorrectly listed as drops from random blocks

### ISSUE THREAD

**Issue by hoolatehip** [KidsDontPlay/BlockDrops#63]
Minecraft 1.12.2
Block Drops 1.4.0
How Fortunate 2.13

In a custom modpack with Block Drops and [How Fortunate](https://www.curseforge.com/minecraft/mc-mods/how-fortunate), the ore chunks that How Fortunate adds are incorrectly listed as dropping from lots of blocks they don't actually drop from. Testing in-game with Fortune III tools confirms that the ore chunks don't actually drop the way JEI says they do; the JEI entry is wrong. 

The affected blocks are from various mods and Vanilla. As far as I can see, the incorrect drops are only the ore chunks from How Fortunate. 

Example excerpts from Block Drops config file: 

>   {
>     "name": "minecraft:wool",
>     "meta": 12,
>     "length": 1,
>     "name0": "fortunate:iron_chunk",
>     "meta0": 0,
>     "0chance0": 0.0,
>     "1chance0": 0.0,
>     "2chance0": 0.0,
>     "3chance0": 0.1,
>     "0pair0": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "1pair0": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "2pair0": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "3pair0": "{\n  \"left\": 0,\n  \"right\": 1\n}"
>   },

>   {
>     "name": "minecraft:red_flower",
>     "meta": 2,
>     "length": 4,
>     "name0": "fortunate:iron_chunk",
>     "meta0": 0,
>     "0chance0": 0.1,
>     "1chance0": 0.0,
>     "2chance0": 0.3,
>     "3chance0": 0.0,
>     "0pair0": "{\n  \"left\": 0,\n  \"right\": 1\n}",
>     "1pair0": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "2pair0": "{\n  \"left\": 0,\n  \"right\": 3\n}",
>     "3pair0": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "name1": "fortunate:gold_chunk",
>     "meta1": 0,
>     "0chance1": 0.0,
>     "1chance1": 0.1,
>     "2chance1": 0.0,
>     "3chance1": 0.4,
>     "0pair1": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "1pair1": "{\n  \"left\": 0,\n  \"right\": 1\n}",
>     "2pair1": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "3pair1": "{\n  \"left\": 0,\n  \"right\": 3\n}",
>     "name2": "fortunate:copper_chunk",
>     "meta2": 0,
>     "0chance2": 0.3,
>     "1chance2": 0.5,
>     "2chance2": 0.2,
>     "3chance2": 0.0,
>     "0pair2": "{\n  \"left\": 0,\n  \"right\": 1\n}",
>     "1pair2": "{\n  \"left\": 0,\n  \"right\": 2\n}",
>     "2pair2": "{\n  \"left\": 0,\n  \"right\": 2\n}",
>     "3pair2": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "name3": "fortunate:iridium_chunk",
>     "meta3": 0,
>     "0chance3": 0.0,
>     "1chance3": 0.0,
>     "2chance3": 0.2,
>     "3chance3": 0.0,
>     "0pair3": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "1pair3": "{\n  \"left\": 0,\n  \"right\": 0\n}",
>     "2pair3": "{\n  \"left\": 0,\n  \"right\": 2\n}",
>     "3pair3": "{\n  \"left\": 0,\n  \"right\": 0\n}"
>   },

This issue on the How Fortunate Curseforge page: [here.](https://www.curseforge.com/minecraft/mc-mods/how-fortunate/issues/12)

**Comment by hoolatehip** [comment]
I tried correcting the Block Drops file by hand. Ran into a couple of problems with that approach: 

1. The file is way too long. I'm running about 200 mods. There are tons of entries that would need to be corrected. 
2. After correcting a few and trying to launch the game, I got a null pointer exception (see below). It's entirely likely that I made a typo somewhere during my hand-corrections that caused the error. 

> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Block Drops (blockdrops)
> Caused by: java.lang.NullPointerException
> 	at mrriegel.blockdrops.util.WrapperJson.deserialize(WrapperJson.java:64)
> 	at mrriegel.blockdrops.util.WrapperJson.deserialize(WrapperJson.java:25)
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
> 	at com.google.gson.Gson.fromJson(Gson.java:887)
> 	at com.google.gson.Gson.fromJson(Gson.java:852)
> 	at mrriegel.blockdrops.BlockDrops.postInit(BlockDrops.java:110)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
> 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
